# Generated by Django 3.2.8 on 2021-10-22 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_counter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictics_data',
            name='views',
            field=models.IntegerField(verbose_name='Количество показов'),
        ),
    ]
