# Generated by Django 3.2.8 on 2021-10-23 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_counter', '0002_alter_statictics_data_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictics_data',
            name='date',
            field=models.DateField(verbose_name='Дата события'),
        ),
    ]
