# Generated by Django 3.2.8 on 2021-10-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_counter', '0003_alter_statictics_data_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statictics_data',
            name='cpc',
            field=models.FloatField(blank=True, null=True, verbose_name='Cредняя стоимость клика'),
        ),
        migrations.AddField(
            model_name='statictics_data',
            name='cpm',
            field=models.FloatField(blank=True, null=True, verbose_name='Cредняя стоимость 1000 показов'),
        ),
        migrations.AlterField(
            model_name='statictics_data',
            name='clicks',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество кликов'),
        ),
        migrations.AlterField(
            model_name='statictics_data',
            name='cost',
            field=models.FloatField(blank=True, null=True, verbose_name='Стоимость кликов'),
        ),
        migrations.AlterField(
            model_name='statictics_data',
            name='views',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество показов'),
        ),
    ]
