# Generated by Django 3.2.8 on 2021-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_counter', '0004_auto_20211024_0802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictics_data',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='Количество кликов'),
        ),
        migrations.AlterField(
            model_name='statictics_data',
            name='cost',
            field=models.FloatField(default=0, verbose_name='Стоимость кликов'),
        ),
        migrations.AlterField(
            model_name='statictics_data',
            name='cpc',
            field=models.FloatField(default=0, verbose_name='Cредняя стоимость клика'),
        ),
        migrations.AlterField(
            model_name='statictics_data',
            name='cpm',
            field=models.FloatField(default=0, verbose_name='Cредняя стоимость 1000 показов'),
        ),
        migrations.AlterField(
            model_name='statictics_data',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата события'),
        ),
        migrations.AlterField(
            model_name='statictics_data',
            name='views',
            field=models.IntegerField(default=0, verbose_name='Количество показов'),
        ),
    ]
