# Generated by Django 3.2.8 on 2021-10-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statistics_counter', '0006_auto_20211027_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statictics_data',
            name='cpc',
            field=models.FloatField(default=0, verbose_name='Cредняя стоимость клика'),
        ),
        migrations.AlterField(
            model_name='statictics_data',
            name='cpm',
            field=models.FloatField(default=0, verbose_name='Cредняя стоимость 1000 показов'),
        ),
    ]
